on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2.1.0

      - name: Check out repository
        uses: actions/checkout@v3

      - name: zig build test
        run: |
          zig env
          zig build test

      - name: zig build cross -Doptimize=ReleaseSmall
        run: |
          zig env
          zig build cross -Doptimize=ReleaseSmall

      - name: Upload artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "zig-out/bin/*.tgz"
