on:
  release:
    types: [created]

name: Add artifacts to release

jobs:
  generate:
    name: Create release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.0

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Build and Test
        run: ./build build test release

      - name: Cross Compile
        run: ./build cross-release cross-tar

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'target/*.tgz'
